INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AF', E'Afghanistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AX', E'Åland Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AL', E'Albania');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'DZ', E'Algeria');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AS', E'American Samoa');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AD', E'Andorra');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AO', E'Angola');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AI', E'Anguilla');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AQ', E'Antarctica');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AG', E'Antigua & Barbuda');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AR', E'Argentina');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AM', E'Armenia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AW', E'Aruba');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AC', E'Ascension Island');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AU', E'Australia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AT', E'Austria');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AZ', E'Azerbaijan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BS', E'Bahamas');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BH', E'Bahrain');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BD', E'Bangladesh');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BB', E'Barbados');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BY', E'Belarus');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BE', E'Belgium');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BZ', E'Belize');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BJ', E'Benin');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BM', E'Bermuda');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BT', E'Bhutan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BO', E'Bolivia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BA', E'Bosnia & Herzegovina');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BW', E'Botswana');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BR', E'Brazil');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IO', E'British Indian Ocean Territory');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'VG', E'British Virgin Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BN', E'Brunei');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BG', E'Bulgaria');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BF', E'Burkina Faso');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BI', E'Burundi');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KH', E'Cambodia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CM', E'Cameroon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CA', E'Canada');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IC', E'Canary Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CV', E'Cape Verde');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BQ', E'Caribbean Netherlands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KY', E'Cayman Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CF', E'Central African Republic');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'EA', E'Ceuta & Melilla');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TD', E'Chad');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CL', E'Chile');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CN', E'China');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CX', E'Christmas Island');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CC', E'Cocos (Keeling) Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CO', E'Colombia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KM', E'Comoros');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CG', E'Congo - Brazzaville');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CD', E'Congo - Kinshasa');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CK', E'Cook Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CR', E'Costa Rica');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CI', E'Côte d’Ivoire');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'HR', E'Croatia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CU', E'Cuba');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CW', E'Curaçao');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CY', E'Cyprus');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CZ', E'Czech Republic');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'DK', E'Denmark');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'DG', E'Diego Garcia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'DJ', E'Djibouti');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'DM', E'Dominica');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'DO', E'Dominican Republic');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'EC', E'Ecuador');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'EG', E'Egypt');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SV', E'El Salvador');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GQ', E'Equatorial Guinea');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ER', E'Eritrea');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'EE', E'Estonia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ET', E'Ethiopia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'FK', E'Falkland Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'FO', E'Faroe Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'FJ', E'Fiji');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'FI', E'Finland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'FR', E'France');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GF', E'French Guiana');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PF', E'French Polynesia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TF', E'French Southern Territories');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GA', E'Gabon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GM', E'Gambia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GE', E'Georgia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'DE', E'Germany');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GH', E'Ghana');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GI', E'Gibraltar');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GR', E'Greece');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GL', E'Greenland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GD', E'Grenada');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GP', E'Guadeloupe');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GU', E'Guam');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GT', E'Guatemala');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GG', E'Guernsey');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GN', E'Guinea');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GW', E'Guinea-Bissau');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GY', E'Guyana');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'HT', E'Haiti');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'HN', E'Honduras');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'HK', E'Hong Kong SAR China');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'HU', E'Hungary');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IS', E'Iceland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IN', E'India');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ID', E'Indonesia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IR', E'Iran');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IQ', E'Iraq');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IE', E'Ireland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IM', E'Isle of Man');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IL', E'Israel');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'IT', E'Italy');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'JM', E'Jamaica');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'JP', E'Japan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'JE', E'Jersey');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'JO', E'Jordan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KZ', E'Kazakhstan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KE', E'Kenya');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KI', E'Kiribati');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'XK', E'Kosovo');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KW', E'Kuwait');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KG', E'Kyrgyzstan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LA', E'Laos');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LV', E'Latvia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LB', E'Lebanon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LS', E'Lesotho');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LR', E'Liberia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LY', E'Libya');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LI', E'Liechtenstein');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LT', E'Lithuania');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LU', E'Luxembourg');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MO', E'Macau SAR China');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MK', E'Macedonia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MG', E'Madagascar');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MW', E'Malawi');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MY', E'Malaysia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MV', E'Maldives');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ML', E'Mali');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MT', E'Malta');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MH', E'Marshall Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MQ', E'Martinique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MR', E'Mauritania');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MU', E'Mauritius');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'YT', E'Mayotte');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MX', E'Mexico');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'FM', E'Micronesia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MD', E'Moldova');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MC', E'Monaco');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MN', E'Mongolia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ME', E'Montenegro');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MS', E'Montserrat');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MA', E'Morocco');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MZ', E'Mozambique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MM', E'Myanmar (Burma)');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NA', E'Namibia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NR', E'Nauru');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NP', E'Nepal');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NL', E'Netherlands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NC', E'New Caledonia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NZ', E'New Zealand');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NI', E'Nicaragua');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NE', E'Niger');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NG', E'Nigeria');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NU', E'Niue');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NF', E'Norfolk Island');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KP', E'North Korea');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MP', E'Northern Mariana Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'NO', E'Norway');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'OM', E'Oman');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PK', E'Pakistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PW', E'Palau');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PS', E'Palestinian Territories');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PA', E'Panama');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PG', E'Papua New Guinea');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PY', E'Paraguay');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PE', E'Peru');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PH', E'Philippines');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PN', E'Pitcairn Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PL', E'Poland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PT', E'Portugal');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PR', E'Puerto Rico');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'QA', E'Qatar');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'RE', E'Réunion');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'RO', E'Romania');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'RU', E'Russia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'RW', E'Rwanda');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'WS', E'Samoa');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SM', E'San Marino');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ST', E'São Tomé & Príncipe');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SA', E'Saudi Arabia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SN', E'Senegal');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'RS', E'Serbia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SC', E'Seychelles');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SL', E'Sierra Leone');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SG', E'Singapore');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SX', E'Sint Maarten');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SK', E'Slovakia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SI', E'Slovenia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SB', E'Solomon Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SO', E'Somalia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ZA', E'South Africa');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GS', E'South Georgia & South Sandwich Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KR', E'South Korea');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SS', E'South Sudan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ES', E'Spain');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LK', E'Sri Lanka');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'BL', E'St. Barthélemy');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SH', E'St. Helena');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'KN', E'St. Kitts & Nevis');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'LC', E'St. Lucia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'MF', E'St. Martin');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'PM', E'St. Pierre & Miquelon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'VC', E'St. Vincent & Grenadines');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SD', E'Sudan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SR', E'Suriname');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SJ', E'Svalbard & Jan Mayen');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SZ', E'Swaziland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SE', E'Sweden');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'CH', E'Switzerland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'SY', E'Syria');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TW', E'Taiwan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TJ', E'Tajikistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TZ', E'Tanzania');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TH', E'Thailand');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TL', E'Timor-Leste');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TG', E'Togo');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TK', E'Tokelau');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TO', E'Tonga');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TT', E'Trinidad & Tobago');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TA', E'Tristan da Cunha');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TN', E'Tunisia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TR', E'Turkey');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TM', E'Turkmenistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TC', E'Turks & Caicos Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'TV', E'Tuvalu');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'UM', E'U.S. Outlying Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'VI', E'U.S. Virgin Islands');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'UG', E'Uganda');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'UA', E'Ukraine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'AE', E'United Arab Emirates');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'GB', E'United Kingdom');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'US', E'United States');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'UY', E'Uruguay');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'UZ', E'Uzbekistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'VU', E'Vanuatu');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'VA', E'Vatican City');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'VE', E'Venezuela');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'VN', E'Vietnam');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'WF', E'Wallis & Futuna');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'EH', E'Western Sahara');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'YE', E'Yemen');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ZM', E'Zambia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES(E'ZW', E'Zimbabwe');
