INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AF', E'Afghanistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ZA', E'Afrique du Sud');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AL', E'Albanie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'DZ', E'Algérie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'DE', E'Allemagne');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AD', E'Andorre');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AO', E'Angola');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AI', E'Anguilla');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AQ', E'Antarctique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AG', E'Antigua-et-Barbuda');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SA', E'Arabie saoudite');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AR', E'Argentine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AM', E'Arménie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AW', E'Aruba');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AU', E'Australie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AT', E'Autriche');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AZ', E'Azerbaïdjan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BS', E'Bahamas');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BH', E'Bahreïn');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BD', E'Bangladesh');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BB', E'Barbade');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BY', E'Bélarus');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BE', E'Belgique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BZ', E'Belize');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BJ', E'Bénin');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BM', E'Bermudes');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BT', E'Bhoutan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BO', E'Bolivie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BA', E'Bosnie-Herzégovine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BW', E'Botswana');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BR', E'Brésil');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BN', E'Brunéi Darussalam');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BG', E'Bulgarie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BF', E'Burkina Faso');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BI', E'Burundi');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KH', E'Cambodge');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CM', E'Cameroun');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CA', E'Canada');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CV', E'Cap-Vert');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'EA', E'Ceuta et Melilla');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CL', E'Chili');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CN', E'Chine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CY', E'Chypre');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CO', E'Colombie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KM', E'Comores');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CG', E'Congo-Brazzaville');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CD', E'Congo-Kinshasa');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KP', E'Corée du Nord');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KR', E'Corée du Sud');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CR', E'Costa Rica');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CI', E'Côte d’Ivoire');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'HR', E'Croatie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CU', E'Cuba');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CW', E'Curaçao');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'DK', E'Danemark');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'DG', E'Diego Garcia');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'DJ', E'Djibouti');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'DM', E'Dominique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'EG', E'Égypte');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AE', E'Émirats arabes unis');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'EC', E'Équateur');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ER', E'Érythrée');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ES', E'Espagne');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'EE', E'Estonie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'VA', E'État de la Cité du Vatican');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'US', E'États-Unis');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ET', E'Éthiopie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'FJ', E'Fidji');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'FI', E'Finlande');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'FR', E'France');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GA', E'Gabon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GM', E'Gambie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GE', E'Géorgie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GS', E'Géorgie du Sud et les îles Sandwich du Sud');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GH', E'Ghana');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GI', E'Gibraltar');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GR', E'Grèce');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GD', E'Grenade');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GL', E'Groenland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GP', E'Guadeloupe');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GU', E'Guam');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GT', E'Guatemala');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GG', E'Guernesey');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GN', E'Guinée');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GQ', E'Guinée équatoriale');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GW', E'Guinée-Bissau');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GY', E'Guyana');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GF', E'Guyane française');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'HT', E'Haïti');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'HN', E'Honduras');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'HU', E'Hongrie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CX', E'Île Christmas');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AC', E'Île de l’Ascension');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IM', E'Île de Man');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NF', E'Île Norfolk');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AX', E'Îles Åland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KY', E'Îles Caïmans');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IC', E'Îles Canaries');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CC', E'Îles Cocos (Keeling)');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CK', E'Îles Cook');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'FO', E'Îles Féroé');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'FK', E'Îles Malouines');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MP', E'Îles Mariannes du Nord');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MH', E'Îles Marshall');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'UM', E'Îles mineures éloignées des États-Unis');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SB', E'Îles Salomon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TC', E'Îles Turques-et-Caïques');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'VG', E'Îles Vierges britanniques');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'VI', E'Îles Vierges des États-Unis');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IN', E'Inde');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ID', E'Indonésie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IQ', E'Irak');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IR', E'Iran');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IE', E'Irlande');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IS', E'Islande');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IL', E'Israël');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IT', E'Italie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'JM', E'Jamaïque');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'JP', E'Japon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'JE', E'Jersey');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'JO', E'Jordanie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KZ', E'Kazakhstan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KE', E'Kenya');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KG', E'Kirghizistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KI', E'Kiribati');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'XK', E'Kosovo');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KW', E'Koweït');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'RE', E'La Réunion');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LA', E'Laos');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LS', E'Lesotho');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LV', E'Lettonie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LB', E'Liban');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LR', E'Libéria');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LY', E'Libye');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LI', E'Liechtenstein');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LT', E'Lituanie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LU', E'Luxembourg');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MK', E'Macédoine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MG', E'Madagascar');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MY', E'Malaisie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MW', E'Malawi');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MV', E'Maldives');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ML', E'Mali');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MT', E'Malte');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MA', E'Maroc');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MQ', E'Martinique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MU', E'Maurice');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MR', E'Mauritanie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'YT', E'Mayotte');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MX', E'Mexique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'FM', E'Micronésie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MD', E'Moldavie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MC', E'Monaco');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MN', E'Mongolie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ME', E'Monténégro');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MS', E'Montserrat');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MZ', E'Mozambique');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MM', E'Myanmar');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NA', E'Namibie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NR', E'Nauru');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NP', E'Népal');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NI', E'Nicaragua');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NE', E'Niger');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NG', E'Nigéria');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NU', E'Niue');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NO', E'Norvège');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NC', E'Nouvelle-Calédonie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NZ', E'Nouvelle-Zélande');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'OM', E'Oman');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'UG', E'Ouganda');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'UZ', E'Ouzbékistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PK', E'Pakistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PW', E'Palaos');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PA', E'Panama');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PG', E'Papouasie-Nouvelle-Guinée');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PY', E'Paraguay');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'NL', E'Pays-Bas');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BQ', E'Pays-Bas caribéens');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PE', E'Pérou');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PH', E'Philippines');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PN', E'Pitcairn');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PL', E'Pologne');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PF', E'Polynésie française');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PR', E'Porto Rico');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PT', E'Portugal');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'QA', E'Qatar');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'HK', E'R.A.S. chinoise de Hong Kong');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MO', E'R.A.S. chinoise de Macao');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CF', E'République centrafricaine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'DO', E'République dominicaine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CZ', E'République tchèque');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'RO', E'Roumanie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'GB', E'Royaume-Uni');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'RU', E'Russie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'RW', E'Rwanda');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'EH', E'Sahara occidental');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'BL', E'Saint-Barthélemy');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'KN', E'Saint-Christophe-et-Niévès');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SM', E'Saint-Marin');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'MF', E'Saint-Martin (France)');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SX', E'Saint-Martin (Pays-Bas)');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PM', E'Saint-Pierre-et-Miquelon');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'VC', E'Saint-Vincent-et-les Grenadines');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SH', E'Sainte-Hélène');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LC', E'Sainte-Lucie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SV', E'Salvador');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'WS', E'Samoa');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'AS', E'Samoa américaines');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ST', E'Sao Tomé-et-Principe');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SN', E'Sénégal');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'RS', E'Serbie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SC', E'Seychelles');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SL', E'Sierra Leone');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SG', E'Singapour');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SK', E'Slovaquie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SI', E'Slovénie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SO', E'Somalie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SD', E'Soudan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SS', E'Soudan du Sud');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'LK', E'Sri Lanka');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SE', E'Suède');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'CH', E'Suisse');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SR', E'Suriname');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SJ', E'Svalbard et Jan Mayen');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SZ', E'Swaziland');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'SY', E'Syrie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TJ', E'Tadjikistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TW', E'Taïwan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TZ', E'Tanzanie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TD', E'Tchad');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TF', E'Terres australes françaises');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'IO', E'Territoire britannique de l’océan Indien');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'PS', E'Territoires palestiniens');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TH', E'Thaïlande');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TL', E'Timor oriental');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TG', E'Togo');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TK', E'Tokelau');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TO', E'Tonga');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TT', E'Trinité-et-Tobago');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TA', E'Tristan da Cunha');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TN', E'Tunisie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TM', E'Turkménistan');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TR', E'Turquie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'TV', E'Tuvalu');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'UA', E'Ukraine');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'UY', E'Uruguay');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'VU', E'Vanuatu');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'VE', E'Venezuela');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'VN', E'Vietnam');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'WF', E'Wallis-et-Futuna');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'YE', E'Yémen');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ZM', E'Zambie');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (E'ZW', E'Zimbabwe');
