INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 8, 'அங்குய்லா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 7, 'அங்கோலா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 16, 'அசர்பைஜான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 9, 'அண்டார்டிகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 5, 'அமெரிக்க சமோவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 227, 'அமெரிக்கா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 103, 'அயர்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 10, 'அர்ஜென்டினா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 12, 'அரூபா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 2, 'அல்பேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 3, 'அல்ஜீரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 5, 'அன்டோரா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 9, 'ஆண்டிகுவா மற்றும் பார்புடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 1, 'ஆப்கானிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 11, 'ஆர்மேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 14, 'ஆஸ்திரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 13, 'ஆஸ்திரேலியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 105, 'இத்தாலி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 99, 'இந்தியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 100, 'இந்தோனேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 200, 'இலங்கை');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 104, 'இஸ்ரேல்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 65, 'ஈக்குவாடோரியல் கினியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 62, 'ஈக்வடார்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 102, 'ஈராக்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 101, 'ஈரான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 223, 'உக்ரைன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 222, 'உகாண்டா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 228, 'உருகுவே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 229, 'உஸ்பெகிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 63, 'எகிப்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 68, 'எதியோப்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 66, 'எரிட்ரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 64, 'எல் சால்வடார்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 67, 'எஸ்டோனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 237, 'ஏமன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 224, 'ஐக்கிய அரபு எமிரேட்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 225, 'ஐக்கிய பேரரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 98, 'ஐஸ்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 161, 'ஓமன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 69, 'ஃபாக்லாந்து தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 70, 'ஃபாரோ தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 71, 'ஃபிஜி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 86, 'க்வாதேலோப்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 174, 'கத்தார்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 36, 'கம்போடியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 91, 'கயானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 88, 'கவுதமாலா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 38, 'கனடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 109, 'கஸகஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 50, 'காங்கோ - கின்ஷாசா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 49, 'காங்கோ - ப்ராஸாவில்லே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 78, 'காம்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 81, 'கானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 55, 'கியூபா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 115, 'கிர்கிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 85, 'கிரனெடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 111, 'கிரிபடி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 84, 'கிரீன்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 83, 'கிரீஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 45, 'கிறிஸ்துமஸ் தீவு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 90, 'கினி-பிஸ்ஸாவ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 89, 'கினியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 51, 'குக் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 54, 'குரோசியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 87, 'குவாம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 114, 'குவைத்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 110, 'கென்யா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 39, 'கேப் வெர்டே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 77, 'கேபான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 37, 'கேமரூன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 40, 'கேமென் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 47, 'கொலம்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 46, 'கோகோஸ் (கீலிங்) தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 53, 'கோட் தி’வாயர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 48, 'கோமரோஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 52, 'கோஸ்டாரிகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 184, 'சமோவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 187, 'சவூதி அரேபியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 42, 'சாட்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 195, 'சாலமன் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 186, 'சாவ் தோம் மற்றும் ப்ரின்சிபி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 185, 'சான் மெரினோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 192, 'சிங்கப்பூர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 191, 'சியர்ரா லியோன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 207, 'சிரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 43, 'சிலி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 44, 'சீனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 202, 'சுரினாம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 201, 'சூடான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 57, 'செக் குடியரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 108, 'செயின்ட் கிட்ஸ் மற்றும் நெவிஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 182, 'செயின்ட் பியர் மற்றும் மிக்வேலான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 181, 'செயின்ட் லூசியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 183, 'செயின்ட் வின்சென்ட் மற்றும் கிரெனடைன்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 179, 'செயின்ட் ஹெலெனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 188, 'செனெகல்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 56, 'சைப்ரஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 196, 'சோமாலியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 216, 'ட்ரினிடாட் மற்றும் டுபாகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 220, 'டர்க்ஸ் மற்றும் கைகோஸ் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 217, 'டுனிசியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 58, 'டென்மார்க்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 61, 'டொமினிகன் குடியரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 60, 'டொமினிகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 214, 'டோகேலோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 213, 'டோகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 215, 'டோங்கா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 211, 'தாய்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 210, 'தான்சானியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 209, 'தாஜிகிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 219, 'துர்க்மெனிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 218, 'துருக்கி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 221, 'துவாலூ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 197, 'தென் ஆப்பிரிக்கா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 113, 'தென் கொரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 198, 'தென் ஜியார்ஜியா மற்றும் தென் சான்ட்விச் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 212, 'தைமூர்-லெஸ்தே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 208, 'தைவான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 147, 'நமீபியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 158, 'நார்ஃபாக் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 160, 'நார்வே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 154, 'நிகரகுவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 157, 'நியூ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 152, 'நியூ கேலிடோனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 153, 'நியூசிலாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 150, 'நெதர்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 149, 'நேபாளம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 155, 'நைஜர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 156, 'நைஜீரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 148, 'நௌரு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 18, 'பங்களாதேஷ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 167, 'பராகுவே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 33, 'பல்கேரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 165, 'பனாமா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 17, 'பஹ்ரைன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 16, 'பஹாமாஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 162, 'பாகிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 166, 'பாப்புவா நியூ கினி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 19, 'பார்படோஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 164, 'பாலஸ்தீனிய பிரதேசங்கள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 163, 'பாலோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 170, 'பிட்கெய்ர்ன் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 173, 'பியூர்டோ ரிகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 73, 'பிரான்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 31, 'பிரிட்டிஷ் இந்தியப் பெருங்கடல் பிரதேசம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 233, 'பிரிட்டீஷ் கன்னித் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 74, 'பிரெஞ்சு கயானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 76, 'பிரெஞ்சு தெற்கு பிரதேசங்கள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 75, 'பிரெஞ்சு பாலினேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 30, 'பிரேசில்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 169, 'பிலிப்பைன்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 72, 'பின்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 34, 'புர்கினா ஃபாஸோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 35, 'புருண்டி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 32, 'புரூனேய்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 25, 'பூடான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 24, 'பெர்முடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 168, 'பெரு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 21, 'பெல்ஜியம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 20, 'பெலாரூஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 22, 'பெலிஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 23, 'பெனின்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 26, 'பொலிவியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 28, 'போட்ஸ்வானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 172, 'போர்ச்சுக்கல்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 171, 'போலந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 27, 'போஸ்னியா மற்றும் ஹெர்ஸிகோவினா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 125, 'மகாவோ எஸ்ஏஆர் சீனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 142, 'மங்கோலியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 127, 'மடகாஸ்கர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 41, 'மத்திய ஆப்ரிக்கக் குடியரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 137, 'மயோத்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 129, 'மலேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 126, 'மாசிடோனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 134, 'மார்டினிக்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 133, 'மார்ஷல் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 132, 'மால்டா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 140, 'மால்டோவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 130, 'மாலத்தீவு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 128, 'மாலவி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 131, 'மாலி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 146, 'மியான்மார் (பர்மா)');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 138, 'மெக்சிகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 236, 'மேற்கு சஹாரா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 139, 'மைக்ரோனேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 145, 'மொசாம்பிக்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 144, 'மொராக்கோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 136, 'மொரிசியஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 141, 'மொனாக்கோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 135, 'மௌரிடானியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 143, 'மௌன்ட்செராட்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 234, 'யூ.எஸ். கன்னித் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 227, 'யூஎஸ் அவுட்லேயிங் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 177, 'ரஷ்யா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 175, 'ரீயூனியன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 176, 'ருமேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 178, 'ருவான்டா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 124, 'லக்ஸ்சம்பர்க்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 117, 'லாட்வியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 116, 'லாவோஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 122, 'லிச்செண்ஸ்டெய்ன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 123, 'லிதுவேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 121, 'லிபியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 119, 'லெசோதோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 118, 'லெபனான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 120, 'லைபீரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 112, 'வட கொரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 159, 'வடக்கு மரியானா தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 230, 'வனுவாட்டு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 94, 'வாடிகன் நகரம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 235, 'வாலிஸ் மற்றும் ஃபுடுனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 232, 'வியட்நாம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 231, 'வெனிசுலா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 107, 'ஜப்பான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 106, 'ஜமைகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 238, 'ஜாம்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 79, 'ஜார்ஜியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 82, 'ஜிப்ரால்டர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 59, 'ஜிபௌட்டி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 239, 'ஜிம்பாப்வே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 80, 'ஜெர்மனி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 108, 'ஜோர்டான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 199, 'ஸ்பெயின்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 193, 'ஸ்லோவாகியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 194, 'ஸ்லோவேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 203, 'ஸ்வல்பார்டு மற்றும் ஜான் மேயன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 204, 'ஸ்வாஸிலாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 206, 'ஸ்விட்சர்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 205, 'ஸ்வீடன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 190, 'ஸேசேல்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 97, 'ஹங்கேரி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 96, 'ஹாங்காங் எஸ்ஏஆர் சீனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 92, 'ஹெய்தி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 95, 'ஹோண்டூராஸ்');