INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 8, 'அங்குய்லா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 7, 'அங்கோலா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 16, 'அசர்பைஜான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 9, 'அண்டார்டிகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 5, 'அமெரிக்க சமோவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 227, 'அமெரிக்கா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 103, 'அயர்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 10, 'அர்ஜென்டினா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, 12, 'அரூபா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AL''அல்பேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, DZ''அல்ஜீரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AD''அன்டோரா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AC''அஷன்ஷியன் தீவு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AG''ஆண்டிகுவா மற்றும் பார்புடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AF''ஆப்கானிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AM''ஆர்மேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AX''ஆலந்து தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AT''ஆஸ்திரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AU''ஆஸ்திரேலியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IT''இத்தாலி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IN''இந்தியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, ID''இந்தோனேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LK''இலங்கை');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IL''இஸ்ரேல்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GQ''ஈக்குவாடோரியல் கினியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145C''ஈக்வடார்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IQ''ஈராக்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IR''ஈரான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, UA''உக்ரைன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, UG''உகாண்டா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, UY''உருகுவே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, UZ''உஸ்பெகிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145G''எகிப்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145T''எதியோப்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145R''எரிட்ரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SV''எல் சால்வடார்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145E''எஸ்டோனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, YE''ஏமன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, AE''ஐக்கிய அரபு எமிரேட்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GB''ஐக்கிய பேரரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IM''ஐல் ஆஃப் மேன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IS''ஐஸ்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, OM''ஓமன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, FK''ஃபாக்லாந்து தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, FO''ஃபாரோ தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, FJ''ஃபிஜி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GP''க்வாதேலோப்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, QA''கத்தார்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KH''கம்போடியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GY''கயானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BQ''கரீபியன் நெதர்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GT''கவுதமாலா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CA''கனடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KZ''கஸகஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CD''காங்கோ - கின்ஷாசா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CG''காங்கோ - ப்ராஸாவில்லே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GM''காம்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GH''கானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CU''கியூபா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KG''கிர்கிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GD''கிரனெடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KI''கிரிபடி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GL''கிரீன்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GR''கிரீஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CX''கிறிஸ்துமஸ் தீவு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GW''கினி-பிஸ்ஸாவ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GN''கினியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CK''குக் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CW''குராகவ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, HR''குரோசியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GU''குவாம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KW''குவைத்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GG''கெர்ன்சி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KE''கென்யா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CV''கேப் வெர்டே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GA''கேபான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CM''கேமரூன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KY''கேமென் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IC''கேனரி தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, XK''கொசோவோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CO''கொலம்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CC''கோகோஸ் (கீலிங்) தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CI''கோட் தி’வாயர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KM''கோமரோஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CR''கோஸ்டாரிகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, WS''சமோவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SA''சவூதி அரேபியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TD''சாட்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SB''சாலமன் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, ST''சாவ் தோம் மற்றும் ப்ரின்சிபி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SM''சான் மெரினோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SG''சிங்கப்பூர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SL''சியர்ரா லியோன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145A''சியூடா மற்றும் மெலில்லா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SY''சிரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CL''சிலி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SX''சின்ட் மார்டென்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CN''சீனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SR''சுரினாம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SD''சூடான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CZ''செக் குடியரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KN''செயின்ட் கிட்ஸ் மற்றும் நெவிஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BL''செயின்ட் பார்தேலெமி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PM''செயின்ட் பியர் மற்றும் மிக்வேலான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MF''செயின்ட் மார்ட்டீன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LC''செயின்ட் லூசியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, VC''செயின்ட் வின்சென்ட் மற்றும் கிரெனடைன்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SH''செயின்ட் ஹெலெனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, RS''செர்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SN''செனெகல்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CY''சைப்ரஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SO''சோமாலியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TT''ட்ரினிடாட் மற்றும் டுபாகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TC''டர்க்ஸ் மற்றும் கைகோஸ் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, DG''டியகோ கார்ஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TA''டிரிஸ்டன் டா குன்ஹா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TN''டுனிசியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, DK''டென்மார்க்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, DO''டொமினிகன் குடியரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, DM''டொமினிகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TK''டோகேலோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TG''டோகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TO''டோங்கா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TH''தாய்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TZ''தான்சானியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TJ''தாஜிகிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TM''துர்க்மெனிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TR''துருக்கி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TV''துவாலூ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SS''தெற்கு சூடான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, ZA''தென் ஆப்பிரிக்கா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KR''தென் கொரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GS''தென் ஜியார்ஜியா மற்றும் தென் சான்ட்விச் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TL''தைமூர்-லெஸ்தே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TW''தைவான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NA''நமீபியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NF''நார்ஃபாக் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NO''நார்வே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NI''நிகரகுவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NU''நியூ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NC''நியூ கேலிடோனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NZ''நியூசிலாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NL''நெதர்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NP''நேபாளம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NE''நைஜர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NG''நைஜீரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, NR''நௌரு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BD''பங்களாதேஷ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PY''பராகுவே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BG''பல்கேரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PA''பனாமா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BH''பஹ்ரைன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BS''பஹாமாஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PK''பாகிஸ்தான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PG''பாப்புவா நியூ கினி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BB''பார்படோஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PS''பாலஸ்தீனிய பிரதேசங்கள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PW''பாலோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PN''பிட்கெய்ர்ன் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PR''பியூர்டோ ரிகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, FR''பிரான்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, IO''பிரிட்டிஷ் இந்தியப் பெருங்கடல் பிரதேசம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, VG''பிரிட்டீஷ் கன்னித் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GF''பிரெஞ்சு கயானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, TF''பிரெஞ்சு தெற்கு பிரதேசங்கள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PF''பிரெஞ்சு பாலினேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BR''பிரேசில்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PH''பிலிப்பைன்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, FI''பின்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BF''புர்கினா ஃபாஸோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BI''புருண்டி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BN''புரூனேய்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BT''பூடான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BM''பெர்முடா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PE''பெரு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BE''பெல்ஜியம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BY''பெலாரூஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BZ''பெலிஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BJ''பெனின்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BO''பொலிவியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BW''போட்ஸ்வானா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PT''போர்ச்சுக்கல்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, PL''போலந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, BA''போஸ்னியா மற்றும் ஹெர்ஸிகோவினா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MO''மகாவோ எஸ்ஏஆர் சீனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MN''மங்கோலியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MG''மடகாஸ்கர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CF''மத்திய ஆப்ரிக்கக் குடியரசு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, YT''மயோத்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MY''மலேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MK''மாசிடோனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MQ''மார்டினிக்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MH''மார்ஷல் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MT''மால்டா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MD''மால்டோவா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MV''மாலத்தீவு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MW''மாலவி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, ML''மாலி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, ME''மான்டேனெக்ரோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MM''மியான்மார் (பர்மா)');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MX''மெக்சிகோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145H''மேற்கு சஹாரா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, FM''மைக்ரோனேஷியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MZ''மொசாம்பிக்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MA''மொராக்கோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MU''மொரிசியஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MC''மொனாக்கோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MR''மௌரிடானியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MS''மௌன்ட்செராட்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, VI''யூ.எஸ். கன்னித் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, UM''யூஎஸ் அவுட்லேயிங் தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, RU''ரஷ்யா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, RE''ரீயூனியன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, RO''ருமேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, RW''ருவான்டா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LU''லக்ஸ்சம்பர்க்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LV''லாட்வியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LA''லாவோஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LI''லிச்செண்ஸ்டெய்ன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LT''லிதுவேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LY''லிபியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LS''லெசோதோ');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LB''லெபனான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, LR''லைபீரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, KP''வட கொரியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, MP''வடக்கு மரியானா தீவுகள்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, VU''வனுவாட்டு');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, VA''வாடிகன் நகரம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, WF''வாலிஸ் மற்றும் ஃபுடுனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, VN''வியட்நாம்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, VE''வெனிசுலா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, JP''ஜப்பான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, JM''ஜமைகா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, ZM''ஜாம்பியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GE''ஜார்ஜியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, GI''ஜிப்ரால்டர்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, DJ''ஜிபௌட்டி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, ZW''ஜிம்பாப்வே');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, JE''ஜெர்சி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, DE''ஜெர்மனி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, JO''ஜோர்டான்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145S''ஸ்பெயின்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SK''ஸ்லோவாகியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SI''ஸ்லோவேனியா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SJ''ஸ்வல்பார்டு மற்றும் ஜான் மேயன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SZ''ஸ்வாஸிலாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, CH''ஸ்விட்சர்லாந்து');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SE''ஸ்வீடன்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, SC''ஸேசேல்ஸ்');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, HU''ஹங்கேரி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, HK''ஹாங்காங் எஸ்ஏஆர் சீனா');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, HT''ஹெய்தி');
INSERT INTO code.country_locales (locale_cd, country_cd, description) VALUES (145, HN''ஹோண்டூராஸ்');